services:
  bot:
    image: ghcr.io/hector-hyrivera/sparky-bot:main
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    networks:
      - bot_network
    restart: unless-stopped

networks:
  bot_network:
    driver: bridge 