version: '3.8'

services:
  bot:
    image: ghcr.io/hector-hyrivera/sparky-bot:latest
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID} 