name = "sparky-bot"
compatibility_date = "2024-09-23"
main = "index.js"
compatibility_flags = ["nodejs_compat"]

# Bind environment variables
[vars]
# CLIENT_ID, DISCORD_TOKEN, and PUBLIC_KEY will be set in the Cloudflare dashboard
# or via wrangler secrets commands 