name = "sparky-bot"
compatibility_date = "2023-10-30"
main = "cloudflare-worker.js"

# Bind environment variables
[vars]
# CLIENT_ID, DISCORD_TOKEN, and PUBLIC_KEY will be set in the Cloudflare dashboard
# or via wrangler secrets commands 