name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        working-directory: serverless
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'serverless'
          secrets: |
            CLIENT_ID
            DISCORD_TOKEN
            PUBLIC_KEY
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }} 