name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Display Wrangler version
      run: pnpm exec wrangler --version
      
    - name: Create .env file
      run: |
        cp env.example .env
        # Populate with placeholder values for testing
        sed -i 's/YOUR_CLIENT_ID_HERE/mock-client-id/' .env
        sed -i 's/YOUR_PUBLIC_KEY_HERE/mock-public-key/' .env
      
    - name: Run tests
      run: pnpm test
      
    - name: Run build
      run: pnpm run build 